### ISSUE TITLE
"Timeout or not connected to KeepassXC" (Windows)

### ISSUE THREAD

**Issue by padhia** [keepassxreboot/keepassxc-browser#64]
## Expected Behavior
The extension should detect running copy of keepassxc 

## Current Behavior
Extension displays "Timeout of not connected to KeepassXC"

## Steps to Reproduce (for bugs)

1. This happens always

## Debug info
```
Connecting to native messaging host org.keepassxc.keepassxc_browser
keepass.js:846 Failed to connect: Specified native messaging host not found.
keepass.js:954 Error 5: Timeout or not connected to KeePassXC
Uncaught (in promise) TypeError: Cannot read property 'onMessage' of null
    at Promise (keepass.js:92)
    at new Promise (<anonymous>)
    at Object.keepass.sendNativeMessage (keepass.js:89)
    at Promise (keepass.js:609)
    at new Promise (<anonymous>)
    at Object.keepass.changePublicKeys (keepass.js:590)
    at setTimeout (event.js:157)
```

## General Info
KeePassXC fork - 2.3.1
keepassxc-browser - 1.0.1

Operating system: Windows
Browser: Chrome
Proxy used: Yes (according to Advanced tab of Browser Integration setting)

## Other relevant information
This used to work with when I had 2.3.0 **portable** version running. With 2.3.1, I deleted the portable version and chose to **install** the .exe file. Ever since then keepassxc-browser can't detect the running copy of KeepassXC. 

Also, when I look at running tasks in Task Manager, I only see `KeePassXC.exe`, however, I remember seeing some tasks with `keepassxc-proxy` with 2.3.0 that I don't see now.

**Comment by varjolintu** [comment]
And you have checked the Chrome option in the Browser Integration settings? If so, please see these steps for troubleshooting: https://github.com/keepassxreboot/keepassxc/issues/1559#issuecomment-369508900

**Comment by padhia** [comment]
Thanks for the prompt response. Information from that link helped!

It turned out that the Windows registry key `org.keepassxc.keepassxc_browser` was pointing to the old path from the portable version (which I deleted). I uninstalled KeePassXC, manually deleted the keys from registry and then reinstalled KeePassXC, the extension then was able to communicate with KeePassXC again.
