### ISSUE TITLE
Stopped working just after update to 1.8.6

### ISSUE THREAD

**Issue by DGarry82** [keepassxreboot/keepassxc-browser#1891]
keepassxc-browser just stopped working at the moment version 1.8.6 just came out.

## Expected Behavior
Should work as it did before (no problems at all during a year or more since i started to use it).

## Current Behavior
1) No "fill" icon in credentials fields
2) Pressing "Connected databases", "Custom login fields" and other links in plugin preferences has no effect at all.
3) KeepassXC itself works fine.

## Steps to Reproduce (for bugs)
1. Update to 1.8.6 (seems it was autoupdate because plugin just stopped working)

## Debug info

`​ [Error init.js:6] KeePassXC-Browser - page.initSettings error: TypeError: Object.hasOwn is not a function
global.js:151 Uncaught (in promise) TypeError: err.at is not a function
    at getFileAndLine (global.js:151)
    at logError (global.js:145)
    at init.js:14
7global.js:151 Uncaught (in promise) TypeError: err.at is not a function
    at getFileAndLine (global.js:151)
    at logError (global.js:145)
    at page.js:128
3global.js:151 Uncaught (in promise) TypeError: err.at is not a function
    at getFileAndLine (global.js:151)
    at logError (global.js:145)
    at page.js:128
getFileAndLine @ global.js:151
logError @ global.js:145
(anonymous) @ page.js:128
Promise.catch (async)
page.switchTab @ page.js:127
(anonymous) @ init.js:62
async function (async)
(anonymous) @ init.js:55
2global.js:151 Uncaught (in promise) TypeError: err.at is not a function
    at getFileAndLine (global.js:151)
    at logError (global.js:145)
    at page.js:128
getFileAndLine @ global.js:151
logError @ global.js:145
(anonymous) @ page.js:128
Promise.catch (async)
page.switchTab @ page.js:127
(anonymous) @ init.js:31
17global.js:151 Uncaught (in promise) TypeError: err.at is not a function
    at getFileAndLine (global.js:151)
    at logError (global.js:145)
    at page.js:128
getFileAndLine @ global.js:151
logError @ global.js:145
(anonymous) @ page.js:128
Promise.catch (async)
page.switchTab @ page.js:127
(anonymous) @ init.js:62
async function (async)
(anonymous) @ init.js:55`

KeePassXC - 2.7.4 AppImage(originally - 2.7.1, upgrade had no effect).
KeePassXC-Browser - 1.8.6 (don't remember original version, but suppose it was 1.8.5)
Operating system: Linux
$ lsb_release -a
Distributor ID: Debian
Description:    Debian GNU/Linux 10 (buster)
Release:        10
Codename:       buster
Browser: Chromium (Version 90.0.4430.212 (Developer Build) built on Debian 10.9, running on Debian 10.12 (64-bit))

**Comment by varjolintu** [comment]
You are using Chrome version that's two years old. Use at least version 93 (which is also old, released in 2021-08-31).

**Comment by DGarry82** [comment]
> You are using Chrome version that's two years old. Use at least version 93 (which is also old, released in 2021-08-31).

Hi! Thank you for you answer. That's a pity, because there's no easy way to update distribution-specific Chromium package. Also, it would be nice to mention browser requiremens somewhere (at least in changelog).

**Comment by varjolintu** [comment]
You are right. Only Firefox was mentioned in the PR and added to `manifest.json`. `minimum_chrome_version` should be added there also.

I suggest you find a PPA solution for Chrome.
